resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    ref: feature/databricks
    endpoint: JFolberth
pool:
  vmImage: 'ubuntu-latest'
parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev2'
      
stages:
  - stage: build_databricks_notebook
    jobs:
      - job: build_databricks_notebook
        steps:
        - task: PublishPipelineArtifact@1
          displayName: 'Publish Pipeline Artifact'
          inputs:
            targetPath: code
            artifact: code
            properties: ''
  - ${{ each environmentObject in parameters.environmentObjects }} : 
    - stage: deploy_databricks_notebook_${{ environmentObject.environmentName }}
      jobs:
        - job: deploy_databricks_notebook_${{ environmentObject.environmentName }}
          variables:
           - name: BUNDLE_ROOT
             value: code
           - name: DATABRICKS_CLIENT_ID
             value: e7e28a74-30b3-4fce-9e38-ceedf0ae7682
           - name: DATABRICKS_HOST
             value: 'https://adb-5130230934145139.19.azuredatabricks.net'
           - group: databricks_dev2
          steps:
            - template: tasks/python_version_task.yml@templates
              parameters:
                versionSpec: '3.10'
            - template: tasks/bash_inline_execute_task.yml@templates
              parameters:
                script: |
                    curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
                    pip install wheel
            - template: tasks/bash_inline_execute_task.yml@templates
              parameters:
                script: databricks bundle validate -t ${{ environmentObject.environmentName }}
    
