resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    ref: feature/databricks
    endpoint: JFolberth
pool:
  vmImage: 'ubuntu-latest'
parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev2'
      
stages:
  - stage: build_databricks_notebook
    jobs:
      - job: build_databricks_notebook
        steps:
        - task: PublishPipelineArtifact@1
          displayName: 'Publish Pipeline Artifact'
          inputs:
            targetPath: code
            artifact: code
            properties: ''
  - ${{ each environmentObject in parameters.environmentObjects }} : 
    - stage: deploy_databricks_notebook_${{ environmentObject.environmentName }}
      jobs:
        - job: deploy_databricks_notebook_${{ environmentObject.environmentName }}
          variables:
           - name: BUNDLE_ROOT
             value: code
           - name: BUNDLE_TARGET
             value: dev2
           - name: DATABRICKS_CLIENT_ID
             value: 6dcbd994-004d-4bf4-87cf-1ed7d1a204b4
           - name: DATABRICKS_HOST
             value: 'https://adb-5130230934145139.19.azuredatabricks.net'
           - group: databricks_dev2
          steps:
            - template: tasks/python_version_task.yml@templates
              parameters:
                versionSpec: '3.10'
            - template: tasks/bash_inline_execute_task.yml@templates
              parameters:
                script: |
                    curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
                    pip install wheel
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: databricks bundle init -t $(Pipeline.Workspace)/code
              env: 
                DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
                DATABRICKS_HOST: $(DATABRICKS_HOST)
                DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)
                BUNDLE_TARGET: $(BUNDLE_TARGET)
            - template: tasks/bash_inline_execute_task.yml@templates
              parameters:
                script: databricks bundle validate -t $(BUNDLE_TARGET)
    
