resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    ref: refs/head/feature/databricks
    endpoint: JFolberth
pool:
  vmImage: 'ubuntu-latest'
parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev2'
      databricksHost: 'https://adb-5130230934145139.19.azuredatabricks.net'
stages:
  - stage: build_databricks_notebook
    jobs:
      - job: build_databricks_notebook
        steps:
        - task: PublishBuildArtifacts@1
          inputs:
            ArtifactName: 'DatabricksBuild'
  - ${{ each environmentObject in parameters.environmentObjects }} : 
    - stage: deploy_databricks_notebook_${{ environmentObject.environmnentName }}
      jobs:
        - job: deploy_databricks_notebook_${{ environmentObject.environmentName }}
          steps:
            - task: 
    
