pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: build_databricks_notebook
    jobs:
      - job: buld_databricks_notebook
        steps:
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: 'code'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/cicd-databricks.zip'
            replaceExistingArchive: true
        
        - task: PublishBuildArtifacts@1
          inputs:
            ArtifactName: 'DatabricksBuild'
