pool:
  vmImage: 'ubuntu-latest'
parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev2'
      databricksHost: 'https://adb-5130230934145139.19.azuredatabricks.net'
stages:
  - stage: build_databricks_notebook
    jobs:
      - job: buld_databricks_notebook
        steps:
        - task: PublishBuildArtifacts@1
          inputs:
            ArtifactName: 'DatabricksBuild'
